version: 2.1

# Set debricked username and password as DEBRICKED_USERNAME and DEBRICKED_PASSWORD respectively,
# inside project settings, to avoid storing them in config. 
# Another option is to set DEBRICKED_TOKEN https://debricked.com/docs/administration/access-tokens.html

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk

    working_directory: ~/repo

    steps:
      - checkout
      - run: mvn dependency:tree -DoutputFile=.debricked-maven-dependencies.tgf -DoutputType=tgf
      # it is important that the generated dependency tree files are persisted and attached to the following scan step
      - persist_to_workspace:
          root: ~/repo
          paths:
            - '*/.debricked-maven-dependencies.tgf'

  scan:
    docker:
      # circleci ignores the entrypoint of debricked-scan, so start the scan manually with a step
      - image: debricked/debricked-scan
    
    working_directory: ~/repo
    
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: bash /circleci.sh

workflows:
  debricked-scan:
    jobs:
      - build
      - scan:
          requires:
            - build
