steps:
  - label: ":shield: Debricked" 
    plugins:
      - docker#v3.2.0:
          image: "debricked/debricked-scan"
          workdir: /app
          environment: 
              - "DEBRICKED_TOKEN"
              - "REPOSITORY_URL=${BUILDKITE_COMMIT}
              - "COMMIT=${BUILDKITE_REPO}"
              - "INTEGRATION_NAME=BuildKite"
              - "BRANCH=${BUILDKITE_BRANCH}"
              - "AUTHOR=${BUILDKITE_BUILD_AUTHOR}"
          entrypoint: ["/common.sh"]
