steps:
  - label: ":shield: Debricked"
    env: 
      REPOSITORY_URL: "${BUILDKITE_REPO}"
      COMMIT: "${BUILDKITE_COMMIT}"
      BRANCH: "${BUILDKITE_BRANCH}"
      AUTHOR: "${BUILDKITE_BUILD_AUTHOR}"
    plugins:
      - docker#v3.2.0:
          image: "debricked/debricked-scan"
          workdir: /app
          environment: 
              - "DEBRICKED_TOKEN"
              - "INTEGRATION_NAME=BuildKite"
              - "REPOSITORY_URL"
              - "COMMIT"
              - "BRANCH"
              - "AUTHOR"
          entrypoint: ["/common.sh"]
