steps:
  - label: "Debricked" 
    plugins:
      - docker#v3.2.0:
          image: "debricked/debricked-scan"
          workdir: /app
          environment: 
              - "DEBRICKED_TOKEN"
          entrypoint: ["/common.sh"]
